export interface Product {
  id: string;
  nombre: string;
  descripcion: string;
  descuento: number;
  image?: string;
  categoria: string;
  stock: number;
  detalle_producto?: {
    marca: string;
    precio_compra: number;
    precio_venta: number;
  };
}

export const products: Product[] = [
  /* {
    id: "1",
    name: 'MacBook Pro 14" M3 Pro',
    description:
      "The most powerful MacBook Pro ever is here. With the blazing-fast M3 Pro chip — the first to be built on 3-nanometer technology — MacBook Pro delivers exceptional performance and amazing battery life.",
    price: 1999.99,
    originalPrice: 2199.99,
    discount: 9,
    image: "/placeholder.svg?height=300&width=300&text=MacBook+Pro",
    category: "Laptops",
    stock: 15,
    rating: 4.8,
    reviews: 124,
    isNew: true,
    featured: true,
    specifications: [
      { name: "Processor", value: "Apple M3 Pro" },
      { name: "RAM", value: "16GB" },
      { name: "Storage", value: "512GB SSD" },
      { name: "Display", value: "14-inch Liquid Retina XDR" },
      { name: "Battery", value: "Up to 18 hours" },
      { name: "Weight", value: "3.5 lbs (1.6 kg)" },
    ],
  },
  {
    id: "2",
    name: "iPhone 15 Pro",
    description:
      "The iPhone 15 Pro is a milestone in the evolution of iPhone design. It has a strong and light aerospace-grade titanium design with a textured matte-glass back.",
    price: 999.99,
    originalPrice: 1099.99,
    discount: 9,
    image: "/placeholder.svg?height=300&width=300&text=iPhone+15+Pro",
    category: "Smartphones",
    stock: 25,
    rating: 4.9,
    reviews: 208,
    isNew: true,
    featured: true,
    specifications: [
      { name: "Processor", value: "A17 Pro chip" },
      { name: "Storage", value: "256GB" },
      { name: "Display", value: "6.1-inch Super Retina XDR" },
      { name: "Camera", value: "48MP main, 12MP ultra wide, 12MP telephoto" },
      { name: "Battery", value: "Up to 23 hours video playback" },
      { name: "Water Resistance", value: "IP68" },
    ],
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    description:
      "Industry-leading noise cancellation optimized for you and enhanced call quality. Magnificent sound, engineered to perfection.",
    price: 349.99,
    originalPrice: 399.99,
    discount: 13,
    image: "/placeholder.svg?height=300&width=300&text=Sony+WH-1000XM5",
    category: "Audio",
    stock: 30,
    rating: 4.7,
    reviews: 156,
    isNew: false,
    featured: true,
    specifications: [
      { name: "Type", value: "Over-ear headphones" },
      { name: "Battery Life", value: "Up to 30 hours" },
      { name: "Noise Cancellation", value: "Yes, adaptive" },
      { name: "Connectivity", value: "Bluetooth 5.2, 3.5mm" },
      { name: "Weight", value: "250g" },
      { name: "Charging", value: "USB-C" },
    ],
  },
  {
    id: "4",
    name: 'iPad Pro 12.9"',
    description:
      "The ultimate iPad experience with the blazing-fast M2 chip, 12.9-inch Liquid Retina XDR display, and support for Apple Pencil and Magic Keyboard.",
    price: 1099.99,
    originalPrice: 1199.99,
    discount: 8,
    image: "/placeholder.svg?height=300&width=300&text=iPad+Pro",
    category: "Tablets",
    stock: 18,
    rating: 4.8,
    reviews: 92,
    isNew: false,
    featured: true,
    specifications: [
      { name: "Processor", value: "Apple M2" },
      { name: "Storage", value: "256GB" },
      { name: "Display", value: "12.9-inch Liquid Retina XDR" },
      { name: "Camera", value: "12MP wide, 10MP ultra wide" },
      { name: "Battery", value: "Up to 10 hours" },
      { name: "Weight", value: "1.5 lbs (682 g)" },
    ],
  },
  {
    id: "5",
    name: "Samsung Galaxy S23 Ultra",
    description:
      "The Samsung Galaxy S23 Ultra is the ultimate smartphone with a built-in S Pen, powerful cameras, and long-lasting battery life.",
    price: 1199.99,
    originalPrice: 1299.99,
    discount: 8,
    image: "/placeholder.svg?height=300&width=300&text=Galaxy+S23+Ultra",
    category: "Smartphones",
    stock: 22,
    rating: 4.7,
    reviews: 178,
    isNew: false,
    featured: true,
    specifications: [
      { name: "Processor", value: "Snapdragon 8 Gen 2" },
      { name: "Storage", value: "256GB" },
      { name: "Display", value: "6.8-inch Dynamic AMOLED 2X" },
      { name: "Camera", value: "200MP main, 12MP ultra wide, 10MP telephoto" },
      { name: "Battery", value: "5000mAh" },
      { name: "Water Resistance", value: "IP68" },
    ],
  },
  {
    id: "6",
    name: "Apple Watch Series 9",
    description:
      "The Apple Watch Series 9 features a new S9 chip, a brighter Always-On Retina display, and a carbon neutral option with the new Sport Loop band.",
    price: 399.99,
    originalPrice: 429.99,
    discount: 7,
    image: "/placeholder.svg?height=300&width=300&text=Apple+Watch",
    category: "Wearables",
    stock: 35,
    rating: 4.6,
    reviews: 112,
    isNew: true,
    featured: true,
    specifications: [
      { name: "Processor", value: "S9 SiP" },
      { name: "Display", value: "Always-On Retina LTPO OLED" },
      { name: "Size", value: "41mm or 45mm" },
      { name: "Water Resistance", value: "50 meters" },
      { name: "Battery", value: "Up to 18 hours" },
      { name: "Sensors", value: "Heart rate, ECG, Blood Oxygen" },
    ],
  },
  {
    id: "7",
    name: "Dell XPS 15",
    description:
      "The Dell XPS 15 combines powerful performance with a stunning 15.6-inch InfinityEdge display in a compact and premium design.",
    price: 1699.99,
    originalPrice: 1899.99,
    discount: 11,
    image: "/placeholder.svg?height=300&width=300&text=Dell+XPS+15",
    category: "Laptops",
    stock: 12,
    rating: 4.5,
    reviews: 86,
    isNew: false,
    featured: false,
    specifications: [
      { name: "Processor", value: "Intel Core i7-13700H" },
      { name: "RAM", value: "16GB" },
      { name: "Storage", value: "512GB SSD" },
      { name: "Display", value: "15.6-inch 3.5K OLED" },
      { name: "Graphics", value: "NVIDIA GeForce RTX 4060" },
      { name: "Battery", value: "Up to 12 hours" },
    ],
  },
  {
    id: "8",
    name: "Sony PlayStation 5",
    description:
      "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.",
    price: 499.99,
    originalPrice: 549.99,
    discount: 9,
    image: "/placeholder.svg?height=300&width=300&text=PlayStation+5",
    category: "Gaming",
    stock: 8,
    rating: 4.9,
    reviews: 245,
    isNew: false,
    featured: true,
    specifications: [
      { name: "CPU", value: "AMD Zen 2, 8 cores" },
      { name: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { name: "Storage", value: "825GB SSD" },
      { name: "Resolution", value: "Up to 8K" },
      { name: "Frame Rate", value: "Up to 120fps" },
      { name: "Ray Tracing", value: "Yes" },
    ],
  },
  {
    id: "9",
    name: "Bose QuietComfort Earbuds II",
    description:
      "The Bose QuietComfort Earbuds II offer the world's best noise cancellation and high-fidelity audio in a comfortable, secure fit.",
    price: 279.99,
    originalPrice: 299.99,
    discount: 7,
    image: "/placeholder.svg?height=300&width=300&text=Bose+QuietComfort",
    category: "Audio",
    stock: 28,
    rating: 4.6,
    reviews: 132,
    isNew: false,
    featured: false,
    specifications: [
      { name: "Type", value: "True wireless earbuds" },
      { name: "Battery Life", value: "Up to 6 hours (24 with case)" },
      { name: "Noise Cancellation", value: "Yes, adaptive" },
      { name: "Connectivity", value: "Bluetooth 5.3" },
      { name: "Water Resistance", value: "IPX4" },
      { name: "Charging", value: "USB-C" },
    ],
  },
  {
    id: "10",
    name: 'LG C3 65" OLED TV',
    description:
      "The LG C3 OLED TV delivers perfect blacks, infinite contrast, and over a billion colors powered by the advanced α9 AI Processor Gen6.",
    price: 1799.99,
    originalPrice: 2099.99,
    discount: 14,
    image: "/placeholder.svg?height=300&width=300&text=LG+C3+OLED",
    category: "TVs",
    stock: 10,
    rating: 4.8,
    reviews: 98,
    isNew: true,
    featured: true,
    specifications: [
      { name: "Display", value: "65-inch 4K OLED" },
      { name: "Resolution", value: "3840 x 2160" },
      { name: "Refresh Rate", value: "120Hz" },
      { name: "HDR", value: "Dolby Vision, HDR10, HLG" },
      { name: "Smart TV", value: "webOS 23" },
      { name: "HDMI", value: "4x HDMI 2.1" },
    ],
  },
  {
    id: "11",
    name: "Google Pixel 8 Pro",
    description:
      "The Google Pixel 8 Pro features Google's most advanced Tensor G3 chip, a stunning 6.7-inch Super Actua display, and a pro-level camera system.",
    price: 899.99,
    originalPrice: 999.99,
    discount: 10,
    image: "/placeholder.svg?height=300&width=300&text=Pixel+8+Pro",
    category: "Smartphones",
    stock: 20,
    rating: 4.7,
    reviews: 115,
    isNew: true,
    featured: false,
    specifications: [
      { name: "Processor", value: "Google Tensor G3" },
      { name: "Storage", value: "128GB" },
      { name: "Display", value: "6.7-inch Super Actua OLED" },
      { name: "Camera", value: "50MP main, 48MP ultra wide, 48MP telephoto" },
      { name: "Battery", value: "5050mAh" },
      { name: "Water Resistance", value: "IP68" },
    ],
  },
  {
    id: "12",
    name: "Microsoft Surface Laptop 5",
    description:
      "The Microsoft Surface Laptop 5 combines style and speed with the latest Intel processors and all-day battery life in a sleek, premium design.",
    price: 999.99,
    originalPrice: 1099.99,
    discount: 9,
    image: "/placeholder.svg?height=300&width=300&text=Surface+Laptop+5",
    category: "Laptops",
    stock: 16,
    rating: 4.5,
    reviews: 78,
    isNew: false,
    featured: false,
    specifications: [
      { name: "Processor", value: "Intel Core i5-1235U" },
      { name: "RAM", value: "8GB" },
      { name: "Storage", value: "256GB SSD" },
      { name: "Display", value: "13.5-inch PixelSense Touch" },
      { name: "Battery", value: "Up to 18 hours" },
      { name: "Weight", value: "2.86 lbs (1.3 kg)" },
    ],
  },
  {
    id: "13",
    name: "Samsung Galaxy Watch 6",
    description:
      "The Samsung Galaxy Watch 6 offers advanced health monitoring, fitness tracking, and smart features in a sleek and durable design.",
    price: 299.99,
    originalPrice: 329.99,
    discount: 9,
    image: "/placeholder.svg?height=300&width=300&text=Galaxy+Watch+6",
    category: "Wearables",
    stock: 32,
    rating: 4.6,
    reviews: 95,
    isNew: true,
    featured: false,
    specifications: [
      { name: "Display", value: "1.3-inch Super AMOLED" },
      { name: "Processor", value: "Exynos W930" },
      { name: "Storage", value: "16GB" },
      { name: "Battery", value: "Up to 40 hours" },
      { name: "Water Resistance", value: "5ATM + IP68" },
      {
        name: "Sensors",
        value: "BioActive Sensor, Temperature, Accelerometer",
      },
    ],
  },
  {
    id: "14",
    name: "Canon EOS R6 Mark II",
    description:
      "The Canon EOS R6 Mark II is a full-frame mirrorless camera that delivers professional-level image quality and 4K video in a compact body.",
    price: 2499.99,
    originalPrice: 2699.99,
    discount: 7,
    image: "/placeholder.svg?height=300&width=300&text=Canon+EOS+R6",
    category: "Cameras",
    stock: 9,
    rating: 4.8,
    reviews: 67,
    isNew: true,
    featured: false,
    specifications: [
      { name: "Sensor", value: "24.2MP Full-Frame CMOS" },
      { name: "Image Processor", value: "DIGIC X" },
      { name: "Autofocus", value: "Dual Pixel CMOS AF II" },
      { name: "Video", value: "4K60p, 1080p120" },
      { name: "Stabilization", value: "5-axis In-Body IS" },
      { name: "Connectivity", value: "Wi-Fi, Bluetooth, USB-C" },
    ],
  },
  {
    id: "15",
    name: "Sonos Era 300",
    description:
      "The Sonos Era 300 is a premium smart speaker with spatial audio capabilities, room-filling sound, and seamless integration with music services.",
    price: 449.99,
    originalPrice: 499.99,
    discount: 10,
    image: "/placeholder.svg?height=300&width=300&text=Sonos+Era+300",
    category: "Speakers",
    stock: 24,
    rating: 4.7,
    reviews: 82,
    isNew: true,
    featured: false,
    specifications: [
      { name: "Audio", value: "Spatial Audio with Dolby Atmos" },
      { name: "Connectivity", value: "Wi-Fi, Bluetooth, AirPlay 2" },
      { name: "Voice Control", value: "Amazon Alexa" },
      { name: "Dimensions", value: "6.3 x 10.2 x 7.3 inches" },
    ],
  }, */
];
